<?php echo $this->doctype() ?>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/img/logo.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl(); ?>/img/logo.png" />
        <meta name="description" content="<?=$this->layout()->metaDescription;?>">
        <meta name="keywords" content="<?=$this->layout()->metaTags;?>">
        <title><?= $this->layout()->pageTitle; ?> :: Starbucks</title>
        <?php
            echo $this->headMeta();
            echo $this->headTitle(); 
            echo $this->headLink();
            echo $this->headScript();
        ?>
        <!--jQuery-->
        <!--<script src="<?php echo $this->baseUrl(); ?>/jquery/jquery-1.12.4.min.js"></script>-->
        <script src="<?php echo $this->baseUrl(); ?>/jquery/jquery.v3.1.1.min.js"></script>
        <!--jQuery-->
        <!--Bootstrap-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/bootstrap/bootstrap-3.3.7/css/bootstrap.min.css">
        <script src="<?php echo $this->baseUrl(); ?>/bootstrap/bootstrap-3.3.7/js/bootstrap.min.js"></script>
        <!--Bootstrap-->
        <!--Data Tables-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/jquery/dataTables/css/jquery.dataTables.min.css">
        <script src="<?php echo $this->baseUrl(); ?>/jquery/dataTables/js/jquery.dataTables.min.js"></script>
        <!--Data Tables-->
        <!--jQuery Sweet Alert-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/sweetalert/css/sweetalert.css">
        <script src="<?php echo $this->baseUrl(); ?>/sweetalert/js/sweetalert.min.js"></script>
        <!--jQuery Sweet Alert-->
        <!--Smoke-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/smoke-v3.1.1/css/smoke.min.css">
        <script src="<?php echo $this->baseUrl(); ?>/smoke-v3.1.1/js/smoke.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/smoke-v3.1.1/lang/es.min.js"></script>
        <!--Smoke-->
        <!--Scroll Top-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/scrolltop/css/scroll.top.css">
        <script src="<?php echo $this->baseUrl(); ?>/scrolltop/js/scroll.top.js"></script>
        <!--Scroll Top-->
        <script>
            var path = "<?php echo $this->baseUrl(); ?>";//por si queremos la url base en js
        </script>
        <script src="<?php echo $this->baseUrl(); ?>/js/script.base.js"></script>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/estilo.base.css">
    </head>
    <body>
        <?php echo $this->partial('nav.phtml'); ?>
        <div id="contenido">
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>